import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const lexendDeca = Lexend_Deca({ 
  weight: "300",
  subsets: ["latin"] 
});
const lexendDeca700 = Lexend_Deca({ 
  weight: "700",
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Guess Number",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lexendDeca.className}>
      <body className="h-screen w-screen flex flex-col bg-black">
        {children}
        <footer className="text-white pb-3 flex justify-end ">
          <p className="pr-3">Made with love by <span className={`${lexendDeca700.className} text-fuchsia-400`}><Link href="/kapi">Fernando</Link></span></p>
        </footer>
      </body>
    </html>
  );
}
